server:
  port: 8080
spring:
  application: # Application-Infos for the Info-Actuator
    name: "@pom.artifactId@"
  # Spring Boot Admin
  boot:
    admin:
      ui:
        title: ${SPRING_BOOT_ADMIN_UI_TITLE:Spring Boot Admin}
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>${SPRING_BOOT_ADMIN_UI_TITLE:Spring Boot Admin}</span>
      discovery: # Filter discovery to tagged services
        instances-metadata:
          spring-boot-admin: true # is added as annotation in service.yaml in helm chart
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        include-not-ready-addresses: true
        discovery-server-url: "http://spring-cloud-kubernetes-discoveryserver"
# for local development (starting directly from IDE), enable port forwarding for discovery server and use the following
# three lines instead of the one above
#        discovery-server-url: "http://localhost:8761"
#  main:
#    cloud-platform: KUBERNETES
management: # Actuator Configuration
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint: # Health-Actuator
    health:
      show-details: always
      probes:
        enabled: true
    env: # Environment-Actuator
      show-values: always
    configprops: # Configuration-Actuator
      show-values: always
  info: # Info-Actuator
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
info: # Application-Infos for the Info-Actuator
  group: "@pom.groupId@"
  artifact: "@pom.artifactId@"
  description: "@pom.description@"
  version: "@pom.version@"
  spring-boot: "@pom.parent.version@"
  spring-boot-admin: "@spring-boot-admin.version@"
  spring-cloud: "@spring-cloud.version@"
  # Tags for the Spring Boot Admin UI
  tags:
    spring-boot: "@pom.parent.version@"
    spring-boot-admin: "@spring-boot-admin.version@"
    spring-cloud: "@spring-cloud.version@"
logging: # Logging-File for the Logfile-Actuator
  file:
    name: "spring-boot-admin.log"
