apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: {{ .Values.deployment.updateStrategy }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.maxUnavailable }}
      maxSurge: {{ .Values.deployment.maxSurge }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: spring-cloud-kubernetes-discoveryserver
      restartPolicy: {{ .Values.deployment.restartPolicy }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.deployment.image }}
        imagePullPolicy: {{ .Values.deployment.pullPolicy }}
        env:
          - name: SPRING_CLOUD_KUBERNETES_HTTP_DISCOVERY_CATALOG_WATCHER_ENABLED
            value: "TRUE"
        {{- with .Values.deployment.env }}
        {{- range $env_var, $key := . }}
          - name: {{ $env_var }}
            value: "{{ $key }}"
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 8761
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8761
          initialDelaySeconds: {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.deployment.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8761
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
