name: spring-boot-admin
namespace: default

deployment:
  env:
    SPRING_BOOT_ADMIN_UI_TITLE: Spring Boot Admin - Kubernetes
  image: spring-boot-admin
  # do not pull image but use locally built image, not recommended for production
  pullPolicy: Never
  updateStrategy: RollingUpdate
  maxSurge: 100%
  maxUnavailable: 0%
  replicas: 2
  restartPolicy: Always
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
  server:
    port: 8080
  management:
    port: 8081
